# set(ALSA_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/include")
list(APPEND ALSA_LIBRARIES "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/lib/libasound.so")
set(ALSA_FOUND True)