set(JACK_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/include")
list(APPEND JACK_LIBRARIES "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/lib/libjack.so")
list(APPEND JACK_LIBRARIES "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/lib/libdb-5.3.so")
set(JACK_FOUND True)