set(GPIOD_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/include")
list(APPEND GPIOD_LIBRARIES "${CMAKE_SOURCE_DIR}/lib/${CMAKE_CXX_COMPILER_TARGET}/lib/libgpiod.so")
set(GPIOD_FOUND True)